### ISSUE TITLE
random nan channels

### ISSUE THREAD

**Issue by jdhenshaw** [jdhenshaw/scousepy#27]
see #26 

So @nicholcunningham has an example where a map with a dud channel in the datacube. The noise calculation doesn't like this very much - the way it currently runs is to remove any spectra where there are nans and then perform the noise computation on a random sample of the remaining pixels. This works for other cubes where, for example, the edge pixels are all nans. However, in this particular example there is a nan located at a specific channel in all pixels. Moreover, @nicholcunningham has another example where there is a dud channel basically at the peak in emission. 

I've temporarily skirted around the issue by allowing the user to trim the spectral axis of the cube (see below). However, I didn't really want to do this as ideally you want to compute the noise from as many channels as possible. The previous use of ppv_vol just specified the fitting range (but the noise was computed from the full spectrum). So all I'm doing is effectively cutting out that dud channel. This doesn't work though if the user doesn't specify a velocity range in ppv_vol. Moreover it isn't very helpful if the dud channel is situated at the peak in emission. Any ideas on this one @keflavich?

Should this be something we make scouse do, or is this a case of having to pre-process the data?

**Comment by keflavich** [comment]
What is a 'dud channel'?  Is it a channel with an incorrect but still numerical value, or a channel with a non-numerical (i.e., nan or inf) value?

**Comment by jdhenshaw** [comment]
non-numerical (nan)

**Comment by keflavich** [comment]
These should be automatically handled by spectral-cube.  If that's not happening, something very serious is going wrong.

**Comment by jdhenshaw** [comment]
what do you mean by "handle"? what does it do exactly?

-- ahh wait this isn't a spectral cube problem this is a scouse problem. What I mean is scouse can't find a single pixel which doesn't contain a nan to do the noise computation (compute_noise in stage_1)

**Comment by keflavich** [comment]
spectral-cube masks out NaN values.  As long as you're using spectral-cube utilities to compute noise, etc, like doing `cube.std(axis=0)`, these values will be ignored.

**Comment by jdhenshaw** [comment]
fixed #28
