### ISSUE TITLE
installation: astropy_helper fails to install automatically

### ISSUE THREAD

**Issue by GiantMolecularCloud** [jdhenshaw/scousepy#31]
I just tried to install scousepy (thanks again for inviting me!) but it failed with the following message:
```
python setup.py install
git submodule command failed unexpectedly:
error: pathspec 'astropy_helpers' did not match any file(s) known to git.
Did you forget to 'git add'?
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
No source found for the 'astropy_helpers' package; astropy_helpers must be available and importable as a prerequisite to building or installing this package.

If the problem persists consider installing astropy_helpers manually using pip
(`pip install astropy_helpers`) or by manually downloading the source archive,
extracting it, and installing by running `python setup.py install` from the
root of the extracted source code.
```
Manually installing astropy_helpers (`pip install astropy_helpers`) solved the issue.

**Comment by jdhenshaw** [comment]
Hey, np! Yes, I am aware of this - I need to update the package such that everything downloads and installs automatically - was meaning to speak to @keflavich about this at some point...

**Comment by GiantMolecularCloud** [comment]
Wasn't sure if this is known already and couldn't find it in the issues list.

**Comment by jdhenshaw** [comment]
Yep this is super helpful - thanks!

**Comment by jdhenshaw** [comment]
ps. if you come across anything else like this, please do add as issues!

**Comment by jdhenshaw** [comment]
resolved
