### ISSUE TITLE
stage directory creation fails in interative run

### ISSUE THREAD

**Issue by GiantMolecularCloud** [jdhenshaw/scousepy#32]
When running scousepy iteratively as described in the tutorial `run_iterative.py`, re-running stage_3 on the full resolution dataset fails because `dataset/stage_3/` cannot be created:

```---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-42-8d5793f11b16> in <module>
      2                    [3.0, 1.0, 3.0, 3.0, 0.5],
      3                    njobs   = 4,
----> 4                    verbose = True
      5                   )

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/scouse.py in stage_3(self, tol, njobs, verbose, spatial, clear_cache, autosave)
    536         self.stagedirs.append(s3dir)
    537         # create the stage_3 directory
--> 538         mkdir_s3(self.outputdirectory, s3dir)
    539
    540         starttime = time.time()

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/io.py in mkdir_s3(outputdir, s3dir)
     52     """
     53     if not os.path.exists(s3dir):
---> 54         os.mkdir(s3dir)
     55     else:
     56         # TODO: error handling

FileNotFoundError: [Errno 2] No such file or directory: './dataset/stage_3'
```

The reason for this error is the missing `dataset/` directory that was never created because stage_1 was not run.
Proposed fix: use  `os.makedirs` instead of `os.mkdir` (the python equivalent of `mkdir -p` vs. `mkdir`) to create the parent directory `dataset/` if needed.

**Comment by jdhenshaw** [comment]
Hey, good catch. I remember messing about with the directory bookkeeping with the tutorials (trying to ensure it was possible to select arbitrary output locations for example),  as I remember it was pretty flakey. 

FYI the iterative fitting was something that @keflavich was writing for big datasets. This could be really useful for you, but I would add that it is really only in the testing phase currently. The basic idea was to downsample the data, fit these, and then use the best fitting solutions to the downsampled data as SAA solutions. You could, in theory, use this as a layered approach to fitting large datasets. Currently however, I would proceed with caution. simple_example_run and refined_grid_example *should* be okay though - with the above caveat about flakey directory bookkeeping.

I have some time today so I will take a look at this.

**Comment by GiantMolecularCloud** [comment]
> iterative fitting ... testing phase currently

Yes, I noticed that and opened another issue on the tutorials repo. It seems not possible to load the tutorial data but it worked with a subset of my dataset.

**Comment by jdhenshaw** [comment]
see PR #39
