### ISSUE TITLE
stage_3 index outf of range on interative runs

### ISSUE THREAD

**Issue by GiantMolecularCloud** [jdhenshaw/scousepy#35]
When running the run_iterative.py tutorial, stage_3 fails with an index out of range error:
```
s = scouse.stage_3(s, [3.0, 1.0, 3.0, 3.0, 0.5], njobs   = 6, verbose = True)
Beginning stage_3 analysis...
Initialising spectra: wsaa = 20.0

|>------------------------------------------------------------------------------------------------|   1 /2.0k ( 0.05%) ETA     0s---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-14-d869f71710a5> in <module>
      2                    [3.0, 1.0, 3.0, 3.0, 0.5],       # SNR treshold, min. velocity width, velo. difference SAA - component (~twice), component separation
      3                    njobs   = 6,
----> 4                    verbose = True
      5                   )

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/scouse.py in stage_3(self, tol, njobs, verbose, spatial, clear_cache, autosave)
    549
    550         # Begin by preparing the spectra and adding them to the relevant SAA
--> 551         initialise_indiv_spectra(self, verbose=verbose, njobs=njobs)
    552
    553         key_set = []

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/stage_3.py in initialise_indiv_spectra(scouseobject, verbose, njobs)
     46         if verbose:
     47             for j in ProgressBar(range(len(saa_dict.keys()))):
---> 48                 prep_spec(j, saa_dict, njobs, scouseobject)
     49         else:
     50             for j in range(len(saa_dict.keys())):

~/anaconda/envs/python3/lib/python3.6/site-packages/scousepy-0.0.dev238-py3.6.egg/scousepy/stage_3.py in prep_spec(j, saa_dict, njobs, scouseobject)
     60
     61     # get the relavent SAA
---> 62     SAA = saa_dict[j]
     63     # Initialise indiv spectra
     64     indiv_spectra = {}

KeyError: 0
```
This is caused by `initialise_indiv_spectra` looping over `range(len(saa_dict.keys()))` instead of the actual keys in ![line 47](https://github.com/jdhenshaw/scousepy/blob/master/scousepy/stage_3.py#L47) of ![stage_3.py](https://github.com/jdhenshaw/scousepy/blob/master/scousepy/stage_3.py).
The `prep_spec` function cannot access the SAA ``saa_dict[0]`` because they start at 642 for some reason.
If the ProgressBar prevents looping over the keys instead of indices, a method to rename the saa keys starting from 0 is needed.

Edit: To clarify: I am running the tutorial code on my own test dataset.

**Comment by jdhenshaw** [comment]
this is....weird....

I can see exactly what you mean but I've no idea why I haven't noticed this before!

edit: Okay I can't understand why your SAA keys would start at anything other than 0. In theory, all SAAs should be contained in the SAA_dict even if they are not included in the fitting during s2. So looping over all keys (starting at 0) *should* be okay. Need to dig into this a bit more.

Can you send me your test dataset and your running script for me to test please?
